// class apiBangkok {

//   late final String cityName;

//   apiBangkok({required this.cityName});

//   factory apiBangkok.fromJson(Map<String,dynamic> json) {
//     final cityName = json['name'];
//     return apiBangkok(cityName: cityName);
//   }
// }

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class apiBangkokSys {
/*
{
  "type": 1,
  "id": 9235,
  "country": "TH",
  "sunrise": 1646782188,
  "sunset": 1646825255
} 
*/

  int? type;
  int? id;
  String? country;
  int? sunrise;
  int? sunset;

  apiBangkokSys({
    this.type,
    this.id,
    this.country,
    this.sunrise,
    this.sunset,
  });
  apiBangkokSys.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toInt();
    id = json['id']?.toInt();
    country = json['country']?.toString();
    sunrise = json['sunrise']?.toInt();
    sunset = json['sunset']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['id'] = id;
    data['country'] = country;
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    return data;
  }
}

class apiBangkokClouds {
/*
{
  "all": 98
} 
*/

  int? all;

  apiBangkokClouds({
    this.all,
  });
  apiBangkokClouds.fromJson(Map<String, dynamic> json) {
    all = json['all']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['all'] = all;
    return data;
  }
}

class apiBangkokWind {
/*
{
  "speed": 4.54,
  "deg": 185,
  "gust": 5.21
} 
*/

  double? speed;
  int? deg;
  double? gust;

  apiBangkokWind({
    this.speed,
    this.deg,
    this.gust,
  });
  apiBangkokWind.fromJson(Map<String, dynamic> json) {
    speed = json['speed']?.toDouble();
    deg = json['deg']?.toInt();
    gust = json['gust']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['speed'] = speed;
    data['deg'] = deg;
    data['gust'] = gust;
    return data;
  }
}

class apiBangkokMain {
/*
{
  "temp": 302.99,
  "feels_like": 305.87,
  "temp_min": 302.1,
  "temp_max": 303.11,
  "pressure": 1009,
  "humidity": 61,
  "sea_level": 1009,
  "grnd_level": 1008
} 
*/

  double? temp;
  double? feelsLike;
  double? tempMin;
  double? tempMax;
  int? pressure;
  int? humidity;
  int? seaLevel;
  int? grndLevel;

  apiBangkokMain({
    this.temp,
    this.feelsLike,
    this.tempMin,
    this.tempMax,
    this.pressure,
    this.humidity,
    this.seaLevel,
    this.grndLevel,
  });
  apiBangkokMain.fromJson(Map<String, dynamic> json) {
    temp = json['temp']?.toDouble();
    feelsLike = json['feels_like']?.toDouble();
    tempMin = json['temp_min']?.toDouble();
    tempMax = json['temp_max']?.toDouble();
    pressure = json['pressure']?.toInt();
    humidity = json['humidity']?.toInt();
    seaLevel = json['sea_level']?.toInt();
    grndLevel = json['grnd_level']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temp'] = temp;
    data['feels_like'] = feelsLike;
    data['temp_min'] = tempMin;
    data['temp_max'] = tempMax;
    data['pressure'] = pressure;
    data['humidity'] = humidity;
    data['sea_level'] = seaLevel;
    data['grnd_level'] = grndLevel;
    return data;
  }
}

class apiBangkokWeather {
/*
{
  "id": 804,
  "main": "Clouds",
  "description": "overcast clouds",
  "icon": "04n"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  apiBangkokWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  apiBangkokWeather.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    main = json['main']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['main'] = main;
    data['description'] = description;
    data['icon'] = icon;
    return data;
  }
}

class apiBangkokCoord {
/*
{
  "lon": 100.52,
  "lat": 13.75
} 
*/

  double? lon;
  double? lat;

  apiBangkokCoord({
    this.lon,
    this.lat,
  });
  apiBangkokCoord.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }
}

class apiBangkok {
/*
{
  "coord": {
    "lon": 100.52,
    "lat": 13.75
  },
  "weather": [
    {
      "id": 804,
      "main": "Clouds",
      "description": "overcast clouds",
      "icon": "04n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 302.99,
    "feels_like": 305.87,
    "temp_min": 302.1,
    "temp_max": 303.11,
    "pressure": 1009,
    "humidity": 61,
    "sea_level": 1009,
    "grnd_level": 1008
  },
  "visibility": 10000,
  "wind": {
    "speed": 4.54,
    "deg": 185,
    "gust": 5.21
  },
  "clouds": {
    "all": 98
  },
  "dt": 1646838572,
  "sys": {
    "type": 1,
    "id": 9235,
    "country": "TH",
    "sunrise": 1646782188,
    "sunset": 1646825255
  },
  "timezone": 25200,
  "id": 1609350,
  "name": "Bangkok",
  "cod": 200
} 
*/

  apiBangkokCoord? coord;
  List<apiBangkokWeather?>? weather;
  String? base;
  apiBangkokMain? main;
  int? visibility;
  apiBangkokWind? wind;
  apiBangkokClouds? clouds;
  int? dt;
  apiBangkokSys? sys;
  int? timezone;
  int? id;
  String? name;
  int? cod;
  String? icon;
  String? desc;

  apiBangkok({
    this.coord,
    this.weather,
    this.base,
    this.main,
    this.visibility,
    this.wind,
    this.clouds,
    this.dt,
    this.sys,
    this.timezone,
    this.id,
    this.name,
    this.cod,
    this.icon,
    this.desc

  });
  apiBangkok.fromJson(Map<String, dynamic> json) {
    coord = (json['coord'] != null) ? apiBangkokCoord.fromJson(json['coord']) : null;
  if (json['weather'] != null) {
  final v = json['weather'];
  final arr0 = <apiBangkokWeather>[];
  v.forEach((v) {
  arr0.add(apiBangkokWeather.fromJson(v));
  });
    weather = arr0;
    }
    base = json['base']?.toString();
    main = (json['main'] != null) ? apiBangkokMain.fromJson(json['main']) : null;
    visibility = json['visibility']?.toInt();
    wind = (json['wind'] != null) ? apiBangkokWind.fromJson(json['wind']) : null;
    clouds = (json['clouds'] != null) ? apiBangkokClouds.fromJson(json['clouds']) : null;
    dt = json['dt']?.toInt();
    sys = (json['sys'] != null) ? apiBangkokSys.fromJson(json['sys']) : null;
    timezone = json['timezone']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    cod = json['cod']?.toInt();
    icon = json['weather'][0]['icon'].toString();
    desc = json['weather'][0]['description'].toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['weather'] = arr0;
    }
    data['base'] = base;
    if (main != null) {
      data['main'] = main!.toJson();
    }
    data['visibility'] = visibility;
    if (wind != null) {
      data['wind'] = wind!.toJson();
    }
    if (clouds != null) {
      data['clouds'] = clouds!.toJson();
    }
    data['dt'] = dt;
    if (sys != null) {
      data['sys'] = sys!.toJson();
    }
    data['timezone'] = timezone;
    data['id'] = id;
    data['name'] = name;
    data['cod'] = cod;
    data['weather'][0]['icon'] = icon;
    data['weather'][0]['description'] = desc;
    return data;
  }

  String get IconURL {
    return 'http://openweathermap.org/img/wn/${icon}@2x.png';
  }
}
