///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class apiKhonkaneSys {
/*
{
  "type": 1,
  "id": 9288,
  "country": "TH",
  "sunrise": 1646868044,
  "sunset": 1646911059
} 
*/

  int? type;
  int? id;
  String? country;
  int? sunrise;
  int? sunset;

  apiKhonkaneSys({
    this.type,
    this.id,
    this.country,
    this.sunrise,
    this.sunset,
  });
  apiKhonkaneSys.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toInt();
    id = json['id']?.toInt();
    country = json['country']?.toString();
    sunrise = json['sunrise']?.toInt();
    sunset = json['sunset']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['id'] = id;
    data['country'] = country;
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    return data;
  }
}

class apiKhonkaneClouds {
/*
{
  "all": 79
} 
*/

  int? all;

  apiKhonkaneClouds({
    this.all,
  });
  apiKhonkaneClouds.fromJson(Map<String, dynamic> json) {
    all = json['all']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['all'] = all;
    return data;
  }
}

class apiKhonkaneWind {
/*
{
  "speed": 1.54,
  "deg": 190
} 
*/

  double? speed;
  int? deg;

  apiKhonkaneWind({
    this.speed,
    this.deg,
  });
  apiKhonkaneWind.fromJson(Map<String, dynamic> json) {
    speed = json['speed']?.toDouble();
    deg = json['deg']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['speed'] = speed;
    data['deg'] = deg;
    return data;
  }
}

class apiKhonkaneMain {
/*
{
  "temp": 305.37,
  "feels_like": 306.75,
  "temp_min": 305.37,
  "temp_max": 305.37,
  "pressure": 1011,
  "humidity": 45
} 
*/

  double? temp;
  double? feelsLike;
  double? tempMin;
  double? tempMax;
  int? pressure;
  int? humidity;

  apiKhonkaneMain({
    this.temp,
    this.feelsLike,
    this.tempMin,
    this.tempMax,
    this.pressure,
    this.humidity,
  });
  apiKhonkaneMain.fromJson(Map<String, dynamic> json) {
    temp = json['temp']?.toDouble();
    feelsLike = json['feels_like']?.toDouble();
    tempMin = json['temp_min']?.toDouble();
    tempMax = json['temp_max']?.toDouble();
    pressure = json['pressure']?.toInt();
    humidity = json['humidity']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temp'] = temp;
    data['feels_like'] = feelsLike;
    data['temp_min'] = tempMin;
    data['temp_max'] = tempMax;
    data['pressure'] = pressure;
    data['humidity'] = humidity;
    return data;
  }
}

class apiKhonkaneWeather {
/*
{
  "id": 803,
  "main": "Clouds",
  "description": "broken clouds",
  "icon": "04d"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  apiKhonkaneWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  apiKhonkaneWeather.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    main = json['main']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['main'] = main;
    data['description'] = description;
    data['icon'] = icon;
    return data;
  }
}

class apiKhonkaneCoord {
/*
{
  "lon": 102.8286,
  "lat": 16.4389
} 
*/

  double? lon;
  double? lat;

  apiKhonkaneCoord({
    this.lon,
    this.lat,
  });
  apiKhonkaneCoord.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }
}

class apiKhonkane {
/*
{
  "coord": {
    "lon": 102.8286,
    "lat": 16.4389
  },
  "weather": [
    {
      "id": 803,
      "main": "Clouds",
      "description": "broken clouds",
      "icon": "04d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 305.37,
    "feels_like": 306.75,
    "temp_min": 305.37,
    "temp_max": 305.37,
    "pressure": 1011,
    "humidity": 45
  },
  "visibility": 9000,
  "wind": {
    "speed": 1.54,
    "deg": 190
  },
  "clouds": {
    "all": 79
  },
  "dt": 1646890602,
  "sys": {
    "type": 1,
    "id": 9288,
    "country": "TH",
    "sunrise": 1646868044,
    "sunset": 1646911059
  },
  "timezone": 25200,
  "id": 1609776,
  "name": "Khon Kaen",
  "cod": 200
} 
*/

  apiKhonkaneCoord? coord;
  List<apiKhonkaneWeather?>? weather;
  String? base;
  apiKhonkaneMain? main;
  int? visibility;
  apiKhonkaneWind? wind;
  apiKhonkaneClouds? clouds;
  int? dt;
  apiKhonkaneSys? sys;
  int? timezone;
  int? id;
  String? name;
  int? cod;
  String? icon;
  String? desc;

  apiKhonkane({
    this.coord,
    this.weather,
    this.base,
    this.main,
    this.visibility,
    this.wind,
    this.clouds,
    this.dt,
    this.sys,
    this.timezone,
    this.id,
    this.name,
    this.cod,
    this.icon,
    this.desc
  });
  apiKhonkane.fromJson(Map<String, dynamic> json) {
    coord = (json['coord'] != null) ? apiKhonkaneCoord.fromJson(json['coord']) : null;
  if (json['weather'] != null) {
  final v = json['weather'];
  final arr0 = <apiKhonkaneWeather>[];
  v.forEach((v) {
  arr0.add(apiKhonkaneWeather.fromJson(v));
  });
    weather = arr0;
    }
    base = json['base']?.toString();
    main = (json['main'] != null) ? apiKhonkaneMain.fromJson(json['main']) : null;
    visibility = json['visibility']?.toInt();
    wind = (json['wind'] != null) ? apiKhonkaneWind.fromJson(json['wind']) : null;
    clouds = (json['clouds'] != null) ? apiKhonkaneClouds.fromJson(json['clouds']) : null;
    dt = json['dt']?.toInt();
    sys = (json['sys'] != null) ? apiKhonkaneSys.fromJson(json['sys']) : null;
    timezone = json['timezone']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    cod = json['cod']?.toInt();
    icon = json['weather'][0]['icon'].toString();
    desc = json['weather'][0]['description'].toString();
    
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['weather'] = arr0;
    }
    data['base'] = base;
    if (main != null) {
      data['main'] = main!.toJson();
    }
    data['visibility'] = visibility;
    if (wind != null) {
      data['wind'] = wind!.toJson();
    }
    if (clouds != null) {
      data['clouds'] = clouds!.toJson();
    }
    data['dt'] = dt;
    if (sys != null) {
      data['sys'] = sys!.toJson();
    }
    data['timezone'] = timezone;
    data['id'] = id;
    data['name'] = name;
    data['cod'] = cod;
    data['weather'][0]['icon'] = icon;
    data['weather'][0]['description'] = desc;
    return data;
  }

  String get IconURL {
    return 'http://openweathermap.org/img/wn/${icon}@2x.png';
  }
}
