///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class apiMahasarakhamSys {
/*
{
  "type": 1,
  "id": 9288,
  "country": "TH",
  "sunrise": 1646867926,
  "sunset": 1646910951
} 
*/

  int? type;
  int? id;
  String? country;
  int? sunrise;
  int? sunset;

  apiMahasarakhamSys({
    this.type,
    this.id,
    this.country,
    this.sunrise,
    this.sunset,
  });
  apiMahasarakhamSys.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toInt();
    id = json['id']?.toInt();
    country = json['country']?.toString();
    sunrise = json['sunrise']?.toInt();
    sunset = json['sunset']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['id'] = id;
    data['country'] = country;
    data['sunrise'] = sunrise;
    data['sunset'] = sunset;
    return data;
  }
}

class apiMahasarakhamClouds {
/*
{
  "all": 35
} 
*/

  int? all;

  apiMahasarakhamClouds({
    this.all,
  });
  apiMahasarakhamClouds.fromJson(Map<String, dynamic> json) {
    all = json['all']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['all'] = all;
    return data;
  }
}

class apiMahasarakhamWind {
/*
{
  "speed": 2.38,
  "deg": 154,
  "gust": 2.4
} 
*/

  double? speed;
  int? deg;
  double? gust;

  apiMahasarakhamWind({
    this.speed,
    this.deg,
    this.gust,
  });
  apiMahasarakhamWind.fromJson(Map<String, dynamic> json) {
    speed = json['speed']?.toDouble();
    deg = json['deg']?.toInt();
    gust = json['gust']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['speed'] = speed;
    data['deg'] = deg;
    data['gust'] = gust;
    return data;
  }
}

class apiMahasarakhamMain {
/*
{
  "temp": 298.44,
  "feels_like": 298.43,
  "temp_min": 298.44,
  "temp_max": 298.44,
  "pressure": 1009,
  "humidity": 54,
  "sea_level": 1009,
  "grnd_level": 992
} 
*/

  double? temp;
  double? feelsLike;
  double? tempMin;
  double? tempMax;
  int? pressure;
  int? humidity;
  int? seaLevel;
  int? grndLevel;

  apiMahasarakhamMain({
    this.temp,
    this.feelsLike,
    this.tempMin,
    this.tempMax,
    this.pressure,
    this.humidity,
    this.seaLevel,
    this.grndLevel,
  });
  apiMahasarakhamMain.fromJson(Map<String, dynamic> json) {
    temp = json['temp']?.toDouble();
    feelsLike = json['feels_like']?.toDouble();
    tempMin = json['temp_min']?.toDouble();
    tempMax = json['temp_max']?.toDouble();
    pressure = json['pressure']?.toInt();
    humidity = json['humidity']?.toInt();
    seaLevel = json['sea_level']?.toInt();
    grndLevel = json['grnd_level']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['temp'] = temp;
    data['feels_like'] = feelsLike;
    data['temp_min'] = tempMin;
    data['temp_max'] = tempMax;
    data['pressure'] = pressure;
    data['humidity'] = humidity;
    data['sea_level'] = seaLevel;
    data['grnd_level'] = grndLevel;
    return data;
  }
}

class apiMahasarakhamWeather {
/*
{
  "id": 802,
  "main": "Clouds",
  "description": "scattered clouds",
  "icon": "03n"
} 
*/

  int? id;
  String? main;
  String? description;
  String? icon;

  apiMahasarakhamWeather({
    this.id,
    this.main,
    this.description,
    this.icon,
  });
  apiMahasarakhamWeather.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    main = json['main']?.toString();
    description = json['description']?.toString();
    icon = json['icon']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['main'] = main;
    data['description'] = description;
    data['icon'] = icon;
    return data;
  }
}

class apiMahasarakhamCoord {
/*
{
  "lon": 103.3008,
  "lat": 16.1772
} 
*/

  double? lon;
  double? lat;

  apiMahasarakhamCoord({
    this.lon,
    this.lat,
  });
  apiMahasarakhamCoord.fromJson(Map<String, dynamic> json) {
    lon = json['lon']?.toDouble();
    lat = json['lat']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['lon'] = lon;
    data['lat'] = lat;
    return data;
  }
}

class apiMahasarakham {
/*
{
  "coord": {
    "lon": 103.3008,
    "lat": 16.1772
  },
  "weather": [
    {
      "id": 802,
      "main": "Clouds",
      "description": "scattered clouds",
      "icon": "03n"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 298.44,
    "feels_like": 298.43,
    "temp_min": 298.44,
    "temp_max": 298.44,
    "pressure": 1009,
    "humidity": 54,
    "sea_level": 1009,
    "grnd_level": 992
  },
  "visibility": 10000,
  "wind": {
    "speed": 2.38,
    "deg": 154,
    "gust": 2.4
  },
  "clouds": {
    "all": 35
  },
  "dt": 1646849728,
  "sys": {
    "type": 1,
    "id": 9288,
    "country": "TH",
    "sunrise": 1646867926,
    "sunset": 1646910951
  },
  "timezone": 25200,
  "id": 1608900,
  "name": "Maha Sarakham",
  "cod": 200
} 
*/

  apiMahasarakhamCoord? coord;
  List<apiMahasarakhamWeather?>? weather;
  String? base;
  apiMahasarakhamMain? main;
  int? visibility;
  apiMahasarakhamWind? wind;
  apiMahasarakhamClouds? clouds;
  int? dt;
  apiMahasarakhamSys? sys;
  int? timezone;
  int? id;
  String? name;
  int? cod;
  String? icon;
  String? desc;


  apiMahasarakham({
    this.coord,
    this.weather,
    this.base,
    this.main,
    this.visibility,
    this.wind,
    this.clouds,
    this.dt,
    this.sys,
    this.timezone,
    this.id,
    this.name,
    this.cod,
    this.icon,
    this.desc
  });
  apiMahasarakham.fromJson(Map<String, dynamic> json) {
    coord = (json['coord'] != null) ? apiMahasarakhamCoord.fromJson(json['coord']) : null;
  if (json['weather'] != null) {
  final v = json['weather'];
  final arr0 = <apiMahasarakhamWeather>[];
  v.forEach((v) {
  arr0.add(apiMahasarakhamWeather.fromJson(v));
  });
    weather = arr0;
    }
    base = json['base']?.toString();
    main = (json['main'] != null) ? apiMahasarakhamMain.fromJson(json['main']) : null;
    visibility = json['visibility']?.toInt();
    wind = (json['wind'] != null) ? apiMahasarakhamWind.fromJson(json['wind']) : null;
    clouds = (json['clouds'] != null) ? apiMahasarakhamClouds.fromJson(json['clouds']) : null;
    dt = json['dt']?.toInt();
    sys = (json['sys'] != null) ? apiMahasarakhamSys.fromJson(json['sys']) : null;
    timezone = json['timezone']?.toInt();
    id = json['id']?.toInt();
    name = json['name']?.toString();
    cod = json['cod']?.toInt();
    icon = json['weather'][0]['icon'].toString();
    desc = json['weather'][0]['description'].toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (coord != null) {
      data['coord'] = coord!.toJson();
    }
    if (weather != null) {
      final v = weather;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['weather'] = arr0;
    }
    data['base'] = base;
    if (main != null) {
      data['main'] = main!.toJson();
    }
    data['visibility'] = visibility;
    if (wind != null) {
      data['wind'] = wind!.toJson();
    }
    if (clouds != null) {
      data['clouds'] = clouds!.toJson();
    }
    data['dt'] = dt;
    if (sys != null) {
      data['sys'] = sys!.toJson();
    }
    data['timezone'] = timezone;
    data['id'] = id;
    data['name'] = name;
    data['cod'] = cod;
    data['weather'][0]['icon'] = icon;
    data['weather'][0]['description'] = desc;
    return data;
  }

  String get IconURL {
    return 'http://openweathermap.org/img/wn/${icon}@2x.png';
  }
}
